version: '3.8'

services:
  minecraft:
    build: .
    container_name: mc-paper-26-3
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "26.3"
      PAPER_CHANNEL: "experimental"
      ONLINE_MODE: "FALSE"
      ENFORCE_WHITELIST: "FALSE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "hayatisasmaz Minecraft Server"
      MOTD: "hayatisasmaz Minecraft Server [Paper 26.3]"
      OPS: "hayatisasmaz"
      ENABLE_RCON: "true"
      RCON_PORT: "25575"
      RCON_PASSWORD: "minecraftrconpass"
      WEB_PASSWORD: "adminoglu123"
      MEMORY: "16G"
      USE_AIKAR_FLAGS: "TRUE"
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
      - "8080:8080/tcp"
    restart: always
